// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zhankui_Wang_Prob_Asst_3_Part_1.Models;

#nullable disable

namespace Zhankui_Wang_Prob_Asst_3_Part_1.Migrations
{
    [DbContext(typeof(CollegeDbContext))]
    [Migration("20240812142452_add_library_fee")]
    partial class add_library_fee
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CourseStudent", b =>
                {
                    b.Property<int>("CoursesId")
                        .HasColumnType("int");

                    b.Property<int>("StudentsStudentID")
                        .HasColumnType("int");

                    b.HasKey("CoursesId", "StudentsStudentID");

                    b.HasIndex("StudentsStudentID");

                    b.ToTable("CourseStudent");
                });

            modelBuilder.Entity("Zhankui_Wang_Prob_Asst_3_Part_1.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int")
                        .HasColumnName("ProvinceID");

                    b.HasKey("Id")
                        .HasName("PK__Cities__3214EC27556039F6");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Zhankui_Wang_Prob_Asst_3_Part_1.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("ProgramId")
                        .HasColumnType("int")
                        .HasColumnName("ProgramID");

                    b.Property<int>("Section")
                        .HasColumnType("int");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Course__3214EC27478F3D59");

                    b.HasIndex("ProgramId");

                    b.ToTable("Course", (string)null);
                });

            modelBuilder.Entity("Zhankui_Wang_Prob_Asst_3_Part_1.Models.FeePolicy", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<double>("AlumniFee")
                        .HasColumnType("float");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("FacilitiesFee")
                        .HasColumnType("float");

                    b.Property<double>("LibraryFee")
                        .HasColumnType("float");

                    b.Property<double>("RegistrationFee")
                        .HasColumnType("float");

                    b.Property<double>("TaxRate")
                        .HasColumnType("float");

                    b.Property<double>("TuitionFee")
                        .HasColumnType("float");

                    b.Property<double>("UnionFee")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("FeePolicy");
                });

            modelBuilder.Entity("Zhankui_Wang_Prob_Asst_3_Part_1.Models.FinancialStatement", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("FeePolicyID")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastChanged")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FeePolicyID");

                    b.HasIndex("StudentID")
                        .IsUnique();

                    b.ToTable("FinancialStatement");
                });

            modelBuilder.Entity("Zhankui_Wang_Prob_Asst_3_Part_1.Models.Program", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Program__3214EC27B0C6B79E");

                    b.ToTable("Program", (string)null);
                });

            modelBuilder.Entity("Zhankui_Wang_Prob_Asst_3_Part_1.Models.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id")
                        .HasName("PK__Province__3214EC27C0E6866E");

                    b.ToTable("Provinces");
                });

            modelBuilder.Entity("Zhankui_Wang_Prob_Asst_3_Part_1.Models.StatementEntry", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FinancialStatementID")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("FinancialStatementID");

                    b.ToTable("StatementEntry");
                });

            modelBuilder.Entity("Zhankui_Wang_Prob_Asst_3_Part_1.Models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProgramId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("StudentID");

                    b.HasIndex("CityId");

                    b.HasIndex("ProgramId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Zhankui_Wang_Prob_Asst_3_Part_1.Models.StudentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id")
                        .HasName("PK__StudentT__3214EC27C1E35886");

                    b.ToTable("StudentTypes");
                });

            modelBuilder.Entity("Zhankui_Wang_Prob_Asst_3_Part_1.Models.Term", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Terms__3214EC27EA474227");

                    b.ToTable("Terms");
                });

            modelBuilder.Entity("CourseStudent", b =>
                {
                    b.HasOne("Zhankui_Wang_Prob_Asst_3_Part_1.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zhankui_Wang_Prob_Asst_3_Part_1.Models.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentsStudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Zhankui_Wang_Prob_Asst_3_Part_1.Models.City", b =>
                {
                    b.HasOne("Zhankui_Wang_Prob_Asst_3_Part_1.Models.Province", "Province")
                        .WithMany("Cities")
                        .HasForeignKey("ProvinceId")
                        .IsRequired()
                        .HasConstraintName("FK__Cities__Province__3D5E1FD2");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("Zhankui_Wang_Prob_Asst_3_Part_1.Models.Course", b =>
                {
                    b.HasOne("Zhankui_Wang_Prob_Asst_3_Part_1.Models.Program", "Program")
                        .WithMany("Courses")
                        .HasForeignKey("ProgramId")
                        .IsRequired()
                        .HasConstraintName("FK__Course__ProgramI__4222D4EF");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("Zhankui_Wang_Prob_Asst_3_Part_1.Models.FinancialStatement", b =>
                {
                    b.HasOne("Zhankui_Wang_Prob_Asst_3_Part_1.Models.FeePolicy", "FeePolicy")
                        .WithMany("FinancialStatements")
                        .HasForeignKey("FeePolicyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zhankui_Wang_Prob_Asst_3_Part_1.Models.Student", "Student")
                        .WithOne("FinancialStatement")
                        .HasForeignKey("Zhankui_Wang_Prob_Asst_3_Part_1.Models.FinancialStatement", "StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeePolicy");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Zhankui_Wang_Prob_Asst_3_Part_1.Models.StatementEntry", b =>
                {
                    b.HasOne("Zhankui_Wang_Prob_Asst_3_Part_1.Models.FinancialStatement", "FinancialStatement")
                        .WithMany("StatementEntries")
                        .HasForeignKey("FinancialStatementID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinancialStatement");
                });

            modelBuilder.Entity("Zhankui_Wang_Prob_Asst_3_Part_1.Models.Student", b =>
                {
                    b.HasOne("Zhankui_Wang_Prob_Asst_3_Part_1.Models.City", "City")
                        .WithMany("Students")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zhankui_Wang_Prob_Asst_3_Part_1.Models.Program", "Program")
                        .WithMany("Students")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("Zhankui_Wang_Prob_Asst_3_Part_1.Models.City", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Zhankui_Wang_Prob_Asst_3_Part_1.Models.FeePolicy", b =>
                {
                    b.Navigation("FinancialStatements");
                });

            modelBuilder.Entity("Zhankui_Wang_Prob_Asst_3_Part_1.Models.FinancialStatement", b =>
                {
                    b.Navigation("StatementEntries");
                });

            modelBuilder.Entity("Zhankui_Wang_Prob_Asst_3_Part_1.Models.Program", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("Zhankui_Wang_Prob_Asst_3_Part_1.Models.Province", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("Zhankui_Wang_Prob_Asst_3_Part_1.Models.Student", b =>
                {
                    b.Navigation("FinancialStatement")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
